### ISSUE TITLE
Fix npm warnings

### ISSUE THREAD

**Issue by kinow** [kinow/cylc-web-gui#7]
`npm install` returns the following errors ATM:

```bash
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2 packages from 3 contributors and audited 31353 packages in 8.897s
found 8 vulnerabilities (1 low, 1 moderate, 5 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by kinow** [comment]
```bash
$ npm audit fix
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 8.033s
fixed 0 of 8 vulnerabilities in 31353 scanned packages
  3 package updates for 8 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or do it by hand)
```

eerrr

**Comment by kinow** [comment]
```bash
$ npm audit fix --force
npm WARN using --force I sure hope you know what you are doing.

> fsevents@1.2.4 install /home/kinow/Development/python/workspace/cylc-web-gui/node_modules/fsevents
> node install

npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@3.1.10 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.4.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.

+ url-loader@1.1.2
+ webpack-dev-server@3.1.10
+ nightwatch@1.0.14
added 143 packages from 506 contributors, removed 31 packages and updated 29 packages in 22.058s
fixed 8 of 8 vulnerabilities in 31353 scanned packages
  3 package updates for 8 vulns involved breaking changes
  (installed due to `--force` option)
```

Then `npm install` gives:

```bash
$ npm install
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.4.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@3.1.10 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.

audited 32127 packages in 9.785s
found 0 vulnerabilities
```

**Comment by kinow** [comment]
And now everything is secure, and everything is broken ( ͡☉ ͜ʖ ͡☉)

```bash
$ npm run dev

> cylc-web-gui@1.0.0 dev /home/kinow/Development/python/workspace/cylc-web-gui
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

The CLI moved into a separate package: webpack-cli
Please install 'webpack-cli' in addition to webpack itself to use the CLI
-> When using npm: npm i -D webpack-cli
-> When using yarn: yarn add -D webpack-cli
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/kinow/Development/python/workspace/cylc-web-gui/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:1)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cylc-web-gui@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cylc-web-gui@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kinow/.npm/_logs/2018-11-28T05_57_03_639Z-debug.log
```

**Comment by kinow** [comment]
Looks like there's a new version of `@vue/cli`, so will have to re-create a template project with the newest release, and start to slowly update it :sob:

**Comment by kinow** [comment]
Already have a skeleton with

- cypress
- mocha chiai
- typescript
- latest versions without vulnerabilities
- Cylc logo :-)
- bootstrap/jquery/popper.js

![image](https://user-images.githubusercontent.com/304786/49250779-a40d5e00-f484-11e8-9064-f60b9ca31e71.png)

**Comment by kinow** [comment]
After some further work, struggling to move all JS code over to TS code (now using class components), I think it's working \o/

```bash
babel.config.js  cypress.json  node_modules  package.json  package-lock.json  postcss.config.js  public  README.md  src  tests  tsconfig.json  tslint.json
kinow@kinow-VirtualBox:~/Development/python/workspace/cylc-web-gui$ npm install
npm WARN eslint-plugin-cypress@2.1.2 requires a peer of eslint@>= 3.2.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 22140 packages in 12.341s
found 0 vulnerabilities
```
